=== YogeshJain96/CoreJava/Day13/day13_help/html xml help/xml help/xml_intro/src/samples2/xml14.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Persons (Person+)>
<!ELEMENT Person (Name, Address, Phone+)>
<!ELEMENT Name (#PCDATA)>

<!ELEMENT Address (FlatNo, State, Country)>
<!ELEMENT FlatNo (#PCDATA)>
<!ELEMENT State (#PCDATA)>
<!ELEMENT Country (#PCDATA)>

<!ELEMENT Phone (#PCDATA)>

<!ATTLIST Phone
    phoneType (work|special|personal) #REQUIRED>

=== YogeshJain96/CoreJava/Day13/day13_help/html xml help/xml help/xml_intro/bin/samples2/xml14.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Persons SYSTEM "xml14.dtd">

<Persons>
    <Person>
        <Name>test1</Name>
        <Address>
            <FlatNo></FlatNo>
            <State></State>
            <Country></Country>
        </Address>
        <Phone phoneType="work"></Phone>
        <Phone phoneType="personal"></Phone>
    </Person>
    
    <Person>
        <Name></Name>
        <Address>
            <FlatNo></FlatNo>
            <State></State>
            <Country></Country>
        </Address>
        <Phone phoneType="special"></Phone>
        <Phone phoneType="work"></Phone>
    </Person>
</Persons>
