<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE Persons [
    
    <!ELEMENT Persons (Person)>
    <!ELEMENT Person (Name, Address, Phone)>
    <!ELEMENT Name (#PCDATA)>
    
    <!ELEMENT Address (StreetName, FlatNo, State, Country)>
    <!ELEMENT StreetName (#PCDATA)>
    <!ELEMENT FlatNo (#PCDATA)>
    <!ELEMENT State (#PCDATA)>
    <!ELEMENT Country (#PCDATA)>

    <!ELEMENT Phone (#PCDATA)>
]>

<Persons>
    <Person>
        <Name></Name>
        <Address>
            <StreetName></StreetName>
            <FlatNo></FlatNo>
            <State></State>
            <Country></Country>
        </Address>
        <Phone></Phone>
    </Person>
</Persons>