=== YogeshJain96/CoreJava/Day13/day13_help/html xml help/xml help/xml_intro/bin/samples3/xml1.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Cars (Car+)>

<!ELEMENT Car (Name, Company, Engine, FuelType, Power)>
<!ELEMENT FuelType (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Company (#PCDATA)>
<!ELEMENT Engine (#PCDATA)>

=== YogeshJain96/CoreJava/Day13/day13_help/html xml help/xml help/xml_intro/bin/samples3/xml1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Cars SYSTEM "xml1.dtd" [

    <!ELEMENT Power (#PCDATA)>
    
    <!ENTITY mh "Mahindra">
    <!ENTITY tata "Tata Pvt. Ltd">

]>

<Cars>
    <Car>
        <Name></Name>
        <Company>&mh;</Company>
        <Engine></Engine>
        <FuelType></FuelType>
        <Power></Power>
    </Car>
    <Car>
        <Name></Name>
        <Company>&tata;</Company>
        <Engine></Engine>
        <FuelType></FuelType>
        <Power></Power>
    </Car>
    <Car>
        <Name></Name>
        <Company></Company>
        <Engine></Engine>
        <FuelType></FuelType>
        <Power></Power>
    </Car>
</Cars>
