<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Persons [
    <!ELEMENT Persons (Person+)>
    <!ELEMENT Person (Name, Address, Phone*)>
    <!ELEMENT Name (#PCDATA)>
    <!ELEMENT Address (#PCDATA)>
    <!ELEMENT Phone (#PCDATA)>

    <!ATTLIST Phone 
        phoneType (work|special|personal) #REQUIRED
        testAtr CDATA #IMPLIED>
]>

<Persons>
    <Person>
        <Name></Name>
        <Address></Address>
        <Phone phoneType="work" testAtr="test"></Phone>
        <Phone phoneType="special"></Phone>
        <Phone phoneType="special"></Phone>
    </Person>
</Persons>
